package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/peterday/valet/internal/store"
)

var (
	syncFormatFlag  string
	syncServiceFlag string
)

var syncCmd = &cobra.Command{
	Use:   "sync [file]",
	Short: "Sync secrets to a file or stdout",
	Long: `Write all secrets from an environment to a file or stdout in various formats.

  valet sync .env -e dev                              # dotenv file (default)
  valet sync --format json -e prod                    # JSON to stdout
  valet sync --format shell -e dev                    # export KEY=val to stdout
  valet sync --format docker -e prod                  # --env KEY=val flags
  valet sync --format k8s-secret -e prod              # Kubernetes Secret YAML
  valet sync --format github-actions -e prod          # >> $GITHUB_ENV format
  valet sync --format compose                         # environment: block for docker-compose
  valet sync --format compose-override --service api  # docker-compose.override.yml`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		env := "dev"
		if envFlag != "" {
			env = envFlag
		}

		// Merge from all linked stores.
		stores, err := openAllStores()
		if err != nil {
			return err
		}

		secrets, err := store.ResolveAllSecretsFlat(stores, env)
		if err != nil {
			return err
		}
		if len(secrets) == 0 {
			return fmt.Errorf("no secrets found in environment %q", env)
		}

		format := syncFormatFlag
		if format == "" {
			if len(args) > 0 {
				format = "dotenv"
			} else {
				format = "dotenv"
			}
		}

		// Get project name for k8s format.
		projectName := "app"
		if primary, pErr := openStore(); pErr == nil {
			if p, pErr := resolveProject(primary); pErr == nil {
				projectName = p
			}
		}

		output, err := formatSecrets(secrets, format, projectName, syncServiceFlag)
		if err != nil {
			return err
		}

		// Write to file or stdout
		if len(args) > 0 {
			filePath := args[0]
			if err := os.WriteFile(filePath, []byte(output), 0600); err != nil {
				return err
			}
			// Add to .gitignore.
			if primary, pErr := openStore(); pErr == nil {
				primary.EnsureGitignore(filePath)
			}
			fmt.Printf("Synced %d %s secrets to %s\n", len(secrets), env, filePath)
		} else {
			fmt.Print(output)
		}

		return nil
	},
}

func formatSecrets(secrets map[string]string, format, project, service string) (string, error) {
	// Sort keys for deterministic output.
	keys := sortedKeys(secrets)

	switch format {
	case "dotenv", "":
		var b strings.Builder
		b.WriteString("# Generated by valet — do not edit manually\n")
		for _, k := range keys {
			v := secrets[k]
			if strings.ContainsAny(v, " \t\n\"'#") {
				v = `"` + strings.ReplaceAll(v, `"`, `\"`) + `"`
			}
			fmt.Fprintf(&b, "%s=%s\n", k, v)
		}
		return b.String(), nil

	case "json":
		data, err := json.MarshalIndent(secrets, "", "  ")
		if err != nil {
			return "", err
		}
		return string(data) + "\n", nil

	case "shell":
		var b strings.Builder
		for _, k := range keys {
			v := secrets[k]
			fmt.Fprintf(&b, "export %s=%s\n", k, shellQuote(v))
		}
		return b.String(), nil

	case "docker":
		var parts []string
		for _, k := range keys {
			parts = append(parts, fmt.Sprintf("--env %s=%s", k, secrets[k]))
		}
		return strings.Join(parts, " ") + "\n", nil

	case "k8s-secret":
		var b strings.Builder
		name := strings.ReplaceAll(project, "_", "-") + "-secrets"
		b.WriteString("apiVersion: v1\n")
		b.WriteString("kind: Secret\n")
		b.WriteString("metadata:\n")
		fmt.Fprintf(&b, "  name: %s\n", name)
		b.WriteString("type: Opaque\n")
		b.WriteString("data:\n")
		for _, k := range keys {
			encoded := base64.StdEncoding.EncodeToString([]byte(secrets[k]))
			fmt.Fprintf(&b, "  %s: %s\n", k, encoded)
		}
		return b.String(), nil

	case "github-actions":
		var b strings.Builder
		for _, k := range keys {
			fmt.Fprintf(&b, "%s=%s\n", k, secrets[k])
		}
		b.WriteString("# Pipe to $GITHUB_ENV: valet sync --format github-actions -e prod >> $GITHUB_ENV\n")
		return b.String(), nil

	case "compose":
		var b strings.Builder
		b.WriteString("# Generated by valet — paste into docker-compose.yml services.<name>.environment\n")
		b.WriteString("environment:\n")
		for _, k := range keys {
			fmt.Fprintf(&b, "  - %s\n", k)
		}
		return b.String(), nil

	case "compose-override":
		svc := service
		if svc == "" {
			svc = project
		}
		var b strings.Builder
		b.WriteString("# Generated by valet — auto-merged by docker compose\n")
		b.WriteString("services:\n")
		fmt.Fprintf(&b, "  %s:\n", svc)
		b.WriteString("    environment:\n")
		for _, k := range keys {
			fmt.Fprintf(&b, "      - %s\n", k)
		}
		return b.String(), nil

	default:
		return "", fmt.Errorf("unknown format %q (supported: dotenv, json, shell, docker, k8s-secret, github-actions, compose, compose-override)", format)
	}
}

func shellQuote(s string) string {
	if strings.ContainsAny(s, " \t\n\"'\\$`!#&|;(){}") {
		return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
	}
	return s
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func init() {
	syncCmd.Flags().StringVar(&syncFormatFlag, "format", "", "output format: dotenv, json, shell, docker, k8s-secret, github-actions, compose, compose-override")
	syncCmd.Flags().StringVar(&syncServiceFlag, "service", "", "service name for compose-override format (default: project name)")
	rootCmd.AddCommand(syncCmd)
}
