package store

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// SyncDotenv writes all secrets from an environment to a .env file.
func (s *Store) SyncDotenv(projectSlug, env, filePath string) error {
	secrets, err := s.GetAllSecretsInEnv(projectSlug, env)
	if err != nil {
		return err
	}

	if len(secrets) == 0 {
		return fmt.Errorf("no secrets found in environment %q", env)
	}

	// Sort keys for deterministic output.
	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by valet — do not edit manually\n")
	for _, k := range keys {
		v := secrets[k]
		// Quote values that contain spaces, newlines, or special chars.
		if strings.ContainsAny(v, " \t\n\"'#\\$`!") {
			v = strings.ReplaceAll(v, `\`, `\\`)
			v = strings.ReplaceAll(v, `"`, `\"`)
			v = strings.ReplaceAll(v, "\n", `\n`)
			v = strings.ReplaceAll(v, "$", `\$`)
			v = `"` + v + `"`
		}
		fmt.Fprintf(&b, "%s=%s\n", k, v)
	}

	if err := os.WriteFile(filePath, []byte(b.String()), 0600); err != nil {
		return err
	}

	// Try to add to .gitignore.
	s.EnsureGitignore(filePath)

	return nil
}

// EnsureGitignore adds the file to .gitignore if not already present.
func (s *Store) EnsureGitignore(filePath string) {
	base := filepath.Base(filePath)
	dir := filepath.Dir(filePath)
	gitignorePath := filepath.Join(dir, ".gitignore")

	data, err := os.ReadFile(gitignorePath)
	if err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			if strings.TrimSpace(line) == base {
				return // already in .gitignore
			}
		}
	}

	f, err := os.OpenFile(gitignorePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return
	}
	defer f.Close()

	if len(data) > 0 && !strings.HasSuffix(string(data), "\n") {
		f.WriteString("\n")
	}
	f.WriteString(base + "\n")
}
